config/routes.rb
SafeUser::Application.routes.draw do
  resources :contacts
  root :to => "contacts#index"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
end

app/models/safe.rb
class Safe < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :safe
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      render action: 'show'
    else
      render action: 'new'
    end
  end

  def update
    @contact = Contact.update(contact_params)
  end

  def destroy
    @contact.destroy
      respond_to do |format|
        format.html { redirect_to contacts_url }
        format.json { head :no_content }
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:email, :phone, :primary)
    end
  end

app/controllers/safe_controller.rb
class SafeController < ApplicationController


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_safe
      @safe = Safe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def safe_params
      params.require(:safe).permit(:key)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/safe_helper.rb
module SafeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
<div class="row">
	<div class="large-12 columns">
		<%= f.label :email %>
		<%= f.email_field :email %>
	</div>
</div>
<div class="row">
	<div class="large-12 columns">
		<%= f.label :phone %>
		<%= f.text_field :phone %>
	</div>
</div>
<div class="row">
	<div class="field">
		<%= f.label :primary %>
		<%= f.check_box :primary %>
	</div>
</div>
<div class="row">
	<%= button_tag(type: 'submit', class: "button expand") do %>
 		Save
	<% end %>
</div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Updating the Contact List</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %>
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing all Contact Information</h1>

<table>
	<thead>
		<tr>
			<th>Email</th>
			<th>Phone Number</th>
			<th>Primary</th>
		</tr>
	</thead>

	<tbody>
		<% @contacts.each do |contact| %>
		<tr>
			<td><%= contact.email %></td>
			<td><%= contact.phone %></td>
			<td><% if contact.primary? %>
						Yes
					<% else %>
						No
					<% end %>
			</td>
			 <td><%= link_to 'Show', contact %></td>
       <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
       <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<p>
	<%= link_to 'Add New Contact', new_contact_path %>
</p>

app/views/contacts/new.html.erb
<h1>New Contact Information</h1>
<%= render 'form' %>

<p><%= link_to 'Cancel', contacts_path %></p>

app/views/contacts/show.html.erb
<h1>Show New Contact</h1>

<p id="notice"><%= notice %></p>

<p>
	<strong>Email: </strong>
	<%= @contact.email %>
</p>

<p>
	<strong>Phone Number: </strong>
	<%= @contact.phone %>
</p>

<p>
	<strong>Primary Contact? </strong>
	<% if @contact.primary? %>
		Yes
	<% else %>
		No
	<% end %>
</p>

<p>
	<%= link_to 'Edit', edit_contact_path(@contact) %>
	<%= link_to 'Delete', @contact, method: :delete, data: { confirm: 'Are you sure?'} %>
	<%= link_to 'Show All', contacts_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>